name: deploy flerkintwo - workflow

on: 
  push: 
    # branches: [main]
    branches: 
      - main

jobs: 
  # deployment: 
  deploy: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v.0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@your.server.ip << 'EOF'
          cd /var/www/flerkintwo
          git pull origin main
          # npm install --production
          # npm run build
          # sudo system restart nginx 
        EOF
  


    # - name: Deploy to Server
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.SSH_HOST_FLERKIN }}
    #     username: ${{ secrets.SSH_USER_FLERKIN }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY_FLERKIN }}
    #     script: |
    #       cd /var/www/flerkintwo
    #       sudo -u www-data git pull origin main

    # - name: Rsync Deployment
    #   uses: burnett01/rsync-deployments@7.1.0
    #   with:
    #     # These secrets should be configured in your repository settings
    #     remote_host: ${{ secrets.SSH_HOST_FLERKIN }}
    #     remote_user: ${{ secrets.SSH_USER_FLERKIN }}
    #     remote_key: ${{ secrets.SSH_PRIVATE_KEY_FLERKIN }}
    #     # The local directory to sync from (e.g., your build output)
    #     path: './' 
    #     # The remote directory to sync to
    #     remote_path: '/var/www/flerkintwo'
    #     # Common rsync flags for deployment
    #     switches: -avzr --delete

    # - name: Rsync to Remote Server
    #   run: |
    #     rsync \
    #       -avzr \
    #       --delete \
    #       -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY_FLERKIN }} -o StrictHostKeyChecking=no" \
    #       ./ \
    #       ${{ secrets.SSH_USER_FLERKIN }}@${{ secrets.SSH_HOST_FLERKIN }}:/var/www/flerkintwo